---
  title: "Music Insights"
  author: "Olivia Lund"
  output: html_document
  df_print: paged
---

First, we need tidyverse to handle data importing and wrangling...

```{R}
#install.packages("tidyverse")

survey <- read.csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/music-survey.csv")
preferences <- read.csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/preferences-survey.csv")

```

The data in the music survey table has inconsistent and verbose naming that isn't conducive to good datakeeping. We can change the column names to better represent 
Cleaning data frame column names:
```{R}
colnames(survey)[colnames(survey)=="Timestamp"]<-"time_submitted"
colnames(survey)[colnames(survey)=="First..we.are.going.to.create.a.pseudonym.for.you.to.keep.this.survey.anonymous..more.or.less...Which.pseudonym.generator.would.you.prefer."]<-"pseudonym_generator"
colnames(survey)[colnames(survey)=="What.is.your.pseudonym."]<-"pseudonym"
colnames(survey)[colnames(survey)=="Sex"]<-"sex"
colnames(survey)[colnames(survey)=="Major"]<-"academic_major"
colnames(survey)[colnames(survey)=="Academic.Year"]<-"academic_level"
colnames(survey)[colnames(survey)=="Year.you.were.born..YYYY."]<-"year_born"
colnames(survey)[colnames(survey)=="Which.musical.instruments.talents.do.you.play...Select.all.that.apply."]<-"instrument_list"
colnames(survey)[colnames(survey)=="Artist"]<-"favorite_song_artist"
colnames(survey)[colnames(survey)=="Song"]<-"favorite_song"
colnames(survey)[colnames(survey)=="Link.to.song..on.Youtube.or.Vimeo."]<-"favorite_song_link"

colnames(survey)

#colnames(survey)[colnames(survey)=="timestamp"]<-"time_submitted" #sidenote: this doesn't work. Why?
```

This dataset completely encapsulates the data, but it describes several types of things, and has columns that describe multiple pieces of information, violating the principles of tidy data. In order to resolve this, the table will need to be neatly divided.

```{R}
library(tidyverse)
library("dplyr")
```


First, let's create a person table with each of the responses from the survey. This table should include pseudonym_generator_name, pseudonym, sex, academic_major, academic_level, year_born, and because we have to store it somewhere, the time they submitted their survey:

```{R}
person<-tibble(pseudonym_generator = survey$pseudonym_generator,  pseudonym = survey$pseudonym, sex = survey$sex, academic_major = survey$academic_major, academic_level = survey$academic_level, year_born = survey$year_born, time_submitted = survey$time_submitted)
colnames(person)
```

Next, in order to store the data that we just took out, let's create a survey table that contains pseudonym, and the name, artist, and url of the person's favorite song.
```{R}
favorite_song<-tibble(pseudonym = survey$pseudonym, favorite_song = survey$favorite_song, favorite_song_artist = survey$favorite_song_artist, favorite_song_link = survey$favorite_song_link)
colnames(favorite_song)
```

Our dataset contains categorical data that we want to remake into discrete data, specifically a factor. To do this, we need to access and modify each of the possible options in that factor:
```{R}
person$academic_level<-as_factor(person$academic_level)
levels(person$academic_level)
person$academic_major<-as_factor(person$academic_major)
levels(person$academic_major)[levels(person$academic_major) == "Computer  Engineering "] <- "Computer Engineering"
levels(person$academic_major)[levels(person$academic_major) == "Computer information systems"] <- "Computer Information Systems"
levels(person$academic_major)
```

We want to take the table of song preferences and use the tidyverse gather function to produce a much tidier table that has the pseudonym artist_song, and rating for every single song:
```{R}
colnames(preferences)[colnames(preferences)=="What.was.your.pseudonym."]<-"pseudonym"
preferences$Timestamp <- NULL
ratings <- gather(preferences, song_name, rating, "X40.crew.Not.Enough":"Wheezer.Buddy.Holly")
colnames(ratings)
```

Next, we want to make a table of the musical talents, lsiting each as a separate row for each person, and combining all the different phrasings combined by talent keyword. 
```{R}
talents <-tibble(pseudonym = survey$pseudonym, talent = survey$instrument)
talents <-talents %>% separate_rows(talent, pseudonym, sep = ", ", convert = TRUE)
#subset(ChickWeight, Diet==4 && Time == 21)
talents$talent <- ifelse(grepl("piano|Piano", talents$talent), "Piano", talents$talent)
talents$talent <- ifelse(grepl("Ukelele", talents$talent), "Ukelele", talents$talent)
colnames(talents)
```

#```{R}
#talents$talent
#ggplot(talents, aes(x = talents$talent)) + geom_histogram()
#```

Some of our data features duplicates. We could resolve this by 

```{R}
temp = inner_join(ratings, person, by="pseudonym")
head(temp)
first <- min(ratings$time_submitted[temp$pseudonym=="Angel Angel"])
ratings <- ratings %>% filter(!(temp$pseudonym=="Angel Angel" & temp$time_submitted!=first))
first <- min(ratings$time_rated[temp$pseudonym=="Mission Theory"])
#ratings <- ratings %>% filter(!(temp$pseudonym=="Mission Theory" & temp$time_submitted!=first))
```


```{R}
#test<=ratings[!(ratings$name %in% ratings$name[ratings$rem == 1]), ]

test<-inner_join(favorite_song, ratings, by="pseudonym")
temp = tibble(test$pseudonym, paste(test$favorite_song_artist, test$favorite_song), test$song_name, test$rating)
test$song_name <- str_replace_all(test$song_name, '[[:punct:]]', " ")
test$song_name <- str_replace_all(test$song_name, "We ll", "We'll")
test$song_name <- str_replace_all(test$song_name, "Can t", "Can't")
test$song_name <- str_replace_all(test$song_name, "She s", "She's")

```

```{R}
person$time_submitted <- as.POSIXlt(parse_datetime(as.character(person$time_submitted), format = "%m/%d/%y %H:%M"))
```