---
title: "Music Insights 2"
author: "Olivia Lund"
output:
  html_document: default
  pdf_document: default
df_print: paged
---

This project is intended to feature predictive analysis using the caret library. I want to analyze the birth years of the students and try to find how effectively we can use other attributes of the person table to predict birth year.

As always, we need to pick our tools:
```{R, results='hide', message=FALSE}
  include <- function(library_name){
    if( !(library_name %in% installed.packages()) )
      install.packages(library_name) 
    library(library_name, character.only=TRUE)
  }
include("caret")
include("dplyr")
include("tidyr")
include("tidyverse")
include("knitr")
#purl("Music Insights.Rmd", output = "part1.r")
#source("part1.r")
```
With that out of the way, we can go ahead and do the important stuff.

I would have liked to include academic_major in this analysis, but due to an issue in which the one computer engineering major would only appear in the test data causing the training model to get confused about the factors present, it had to be omitted. In addition, somehow one student's birth year was NA and had to be omitted for this analysis.
```{R}
person <- subset(person, !is.na(person$year_born))
sample_selection <- createDataPartition(person, p = 0.75, list = FALSE)
train <- person[sample_selection, ]
test <- person[-sample_selection, ]
```


One of the most effective ways of gathering insight about the change in a variable is by seeing how well it correlates with another one. In this case, we're seeing how well the target variable, birth_year, correlates with every other variable. A larger value means a higher correlation.
```{R}
submission_model <- lm(data=train, formula = person$year_born ~ person$sex + person$academic_level)
summary(submission_model)
```
As we can see from these results, none of the variables correlate exceptionally well, with academic major being the strongest correlation. 

Now, we can use the predictive model we trained on 75% of the data earlier to make a prediction for the birth year of the other 25%. 
```{R}
predictions <- submission_model %>% predict(test)
predictions
#as.Date(predictions,origin = "1960-10-01")
```
The results of this testing model produce fairly reasonable results. These results have quirks to them, like how whereas the training data was integer years, these results are all decimal values. 


Further analysis has proven difficult because of syntax errors in analysis code. This project will have to stop here for now, and hopefully will be made up in the second part of the portfolio project.